let msg = 
    {classes:[
        [{canyin:'餐饮'},
            {
                hotpot:'火锅',
                tea_dringking:'茶饮',
                baking:'烘焙',
                snack:'小吃',
                fastfood:'快餐',
                coffee:'咖啡',
                chin:'中餐',
                westernfood:'西餐',
                noodle:'面馆',
                suger:'甜品',
                delicatessen:'熟食',
                jap:'日式料理',
                kore:'韩式料理'
            }
        ],
        [{edu:'教育培训'},
            {
                k12:'k12',
                one:'一对一',
                english:'英语',
                early_edu:'早教',
                intell:'智力开发',
                robot:'教育机器人',
                pro:'编程',
                adult_edu:'成人教育'
            }
        ],
        [{fastmoving:'快消'},
            {
                drink:'酒水',
                snacks:'零食',
                cosmetic:'化妆品',
                cleaning:'清洁用品',
                stationery:'文化用品',
                dairy:'乳制品'
            }
        ],
        [{health:'保健'},
            {
                healthfood:'保健食品',
                healthmuseum:'养生馆',
                gym:'健身房',
                beauty:'美容美体',
                care:'个人护理'
            }
        ],
        [{mother:'母婴'},
            {
                m_clothing:'母婴服装',
                milk:'奶粉',
                diapers:'尿不湿',
                baby:'婴幼儿用品'
            }
        ],
        [{retail:'零售'},
            {
                market:'超市',
                stroe:'便利店'
            }
        ],
        [{building:'建材'},
            {
                hardware:'五金',
                ceiling:'吊顶',
                floor:'地板',
                paint:'油漆',
                wallpaper:'墙纸',
                tile:'瓷砖',
                bothroom:'卫浴',
                lighting:'灯饰',
                window:'门窗',
                env_pro:'环保'
            }
        ],
        [{clothing:'服装'},
            {
                c_clothing:'童装',
                a_clothing:'成装',
                m_clothing:'男装',
                w_clothing:'女装',
                me_clothing:'中老年装',
            }
        ],
        [{furniture:'家具'},
            {}
        ],
        [{textiles:'家纺'},
            {}
        ],
        [{hotel:'酒店'},
            {
                bus_hotel:'商务酒店',
                bou_hotel:'精品酒店',
                supply:'酒店用品'
            }
        ],
    ],
    chuzongfang:{
        index:['canyin/images/chuzongfang/roujiamologo.jpg'],
        dianpu:{
            ins:'canyin',
            program:{
                title:'褚宗坊 疯狂肉夹馍',
                money:'5万',
                time:'1997年',
                instudry:'餐饮',
                count:'50多家',
                area:'全国',
                people:'所有人',
                scope:'肉夹馍，面食，米饭',
                auth:'附近两公里之内不会有第二家',
                birthplace:'山东',
                contract:'',
                train:'7-15天',
                royalties:'',
                condition:'',
                margin:'',
                initial:'4万'
            },
            company:{
                name:'山东褚宗坊餐饮管理有限公司',
                nature:'有限公司',
                funds:'300万元',
                location:'山东'
            },
            big:['canyin/images/chuzongfang/big1.jpg','canyin/images/chuzongfang/big2.jpg','canyin/images/chuzongfang/big3.jpg','canyin/images/chuzongfang/big4.jpg'],
            good:['canyin/images/chuzongfang/good1.jpg','canyin/images/chuzongfang/good2.jpg','canyin/images/chuzongfang/good3.jpg','canyin/images/chuzongfang/good4.jpg'],
            xiangmu:['canyin/images/chuzongfang/xiangmu1.jpg','canyin/images/chuzongfang/xiangmu2.jpg'],
            youshi:['canyin/images/chuzongfang/youshi1.jpg','canyin/images/chuzongfang/youshi2.jpg','canyin/images/chuzongfang/youshi3.jpg'],
            liucheng:['canyin/images/chuzongfang/liucheng1.jpg','canyin/images/chuzongfang/liucheng2.jpg','canyin/images/chuzongfang/liucheng3.jpg']
        },
        dianpuindex:['canyin/images/chuzongfang/roujiamo1.jpg','canyin/images/chuzongfang/roujiamo2.jpg','canyin/images/chuzongfang/roujiamo3.jpg','canyin/images/chuzongfang/roujiamo4.jpg','canyin/images/chuzongfang/roujiamo5.jpg','canyin/images/chuzongfang/roujiamo6.jpg',]
    },    
    xiaobao:{
        index:[],
        dianpu:{
            program:{
                title:'UCC干洗',
                money:'5~10万',
                time:'2013-06-07',
                instudry:'干洗',
                count:'10000家',
                area:'全国',
                people:'自由创业',
                scope:'干洗店加盟',
                auth:'是',
                birthplace:'上海',
                contract:'',
                train:'',
                royalties:'',
                condition:'',
                margin:'',
                initial:''
            },
            company:{
                name:'上海云端洗烫设备集团有限公司',
                nature:'有限责任公司',
                funds:'1000万元',
                location:'上海市宝山区沪太'
            }
        },
        dianpuindex:[]
    }};
let mess = JSON.stringify(msg);
function getData(){
    return mess;
}