<?php exit;?>2018-11-09 21:29:34<section style="box-sizing: border-box;"><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; width: 100%; vertical-align: top; background-color: rgb(204, 64, 52); padding: 15px; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="display: inline-block; width: 100%; vertical-align: top; background-color: rgb(255, 243, 224); padding: 10px; box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0% 0px; position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; letter-spacing: 0px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">本周开始，小宝招商将汇聚行业优秀的品牌，分享他们的招商经验。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">这周，我们给大家分享一家茶馆品牌的成功故事。</p>
</section></section></section> </section></section></section> </section></section>鹿角巷</section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; text-align: center; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: top; box-sizing: border-box;">  <section style="width: 6px; height: 6px; border-radius: 100%; float: left; margin-top: -14px; background-color: rgb(26, 35, 126); box-sizing: border-box;"></section> <section style="width: 6px; height: 6px; border-radius: 100%; float: right; margin-top: -14px; background-color: rgb(26, 35, 126); box-sizing: border-box;"></section> <section style="clear: both; box-sizing: border-box;"></section> </section> <section style="border: 2px solid rgb(26, 35, 126); margin-top: -12px; padding: 18px 10px 10px; border-radius: 0px; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0%; position: static; box-sizing: border-box;"><section style="max-width: 100%; vertical-align: middle; display: inline-block; width: 100%; border-bottom: 0px solid rgb(62, 62, 62); border-bottom-right-radius: 0px; box-sizing: border-box;"><img src="http://img.xiumi.us/xmi/ua/1reMW/i/d702a5eb75b1405bbfe389005afc8b03-sz_628618.png" style="vertical-align: middle; max-width: 100%; width: 100%; box-sizing: border-box;" data-ratio="0.696875" data-w="640" _width="100%" alt="" /></section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 10px; position: static; box-sizing: border-box;"><section style="width: 100%; height: 5px; background-color: rgb(33, 150, 243); box-sizing: border-box;"> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0% 0px; position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">在餐饮行业里，卖水的毛利，永远要高于卖餐的。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">当万业都在资本寒冬里艰难过冬的时候，饮品却一枝独秀，自2015年以来，共有14个饮品品牌获得过融资，其中规模过亿的就有5起。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">各大茶饮品牌在今年也都有不俗表现，喜茶、奈雪依旧春风得意，而答案茶、一点点的走红更是将整个茶饮市场推向了高潮，饮品市场进入了前所未有的疯狂期。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">喧嚣之下却也隐藏着令人揪心的实情，比如70%的跟随型饮品都活不过一年，大品牌也都难逃被模仿、被抢注的命运。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">到底真实的茶饮市场是怎样的？又该如何突围？</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">也许，在这个问题上鹿角巷的创始人邱茂庭最有发言权，从台北一家不起眼的奶茶店，到5年时间在全球拥有200家直营店，他享受过站在巅峰的快感；</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">实际门店200家，冒牌店却是它的5倍，他也经历过落入谷底的疼痛。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">近日，我们就与鹿角巷的创始人邱茂庭展开了一场对话。</p>
</section></section></section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 34px 0% 8px; position: static; box-sizing: border-box;"><section style="background-color: rgb(105, 143, 187); height: 1px; box-sizing: border-box;"></section> </section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: -24px 0% 10px; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 2px solid rgba(255, 255, 255, 0); padding: 0.1em 0.3em; background-color: rgb(105, 143, 187); color: rgb(255, 255, 255); font-size: 15px; line-height: 2; text-align: center; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">以下是邱茂庭自诉内容</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: center; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">卖水毛利很高，但你要了解这些真相</strong></p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: center; margin-top: 10px; margin-bottom: 10px; position: static; box-sizing: border-box;"><section style="max-width: 100%; vertical-align: middle; display: inline-block; box-sizing: border-box;"><img src="http://statics.xiumi.us/stc/images/templates-assets/tpl-paper/image/3b2123624607795d9bd83c5792d36917-sz_5855.png" style="vertical-align: middle; max-width: 100%; box-sizing: border-box;" data-ratio="0.1078125" data-w="640" alt="" /></section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: center; margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0.5em 0px; position: static; box-sizing: border-box;"><section style="border-top: 1px dashed rgb(171, 171, 171); box-sizing: border-box;"></section></section></section> </section><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0%; font-size: 15px; position: static; box-sizing: border-box;"><section style="display: inline-block; margin-bottom: -0.9em; overflow: hidden; box-sizing: border-box;"> <section style="width: 1.76em; height: 0.5em; margin-bottom: -0.5em; margin-left: 0.25em; border-left: 1px solid rgb(106, 226, 250); border-right: 1px solid rgb(106, 226, 250); transform: skew(-45deg); -webkit-transform: skew(-45deg); -moz-transform: skew(-45deg); -o-transform: skew(-45deg); box-sizing: border-box;"></section> <section style="width: 1.8em; height: 1.8em; margin-left: 0.5em; background-color: rgb(93, 208, 230); box-sizing: border-box;"> </section> <section style="width: 1.2em; height: 1.2em; margin-top: -0.88em; line-height: 1.2em; background-color: rgb(106, 226, 250); color: rgb(255, 255, 255); font-size: 23px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">1</p>
</section> <section style=" transform: rotate(-45deg); -webkit-transform: rotate(-45deg); -moz-transform: rotate(-45deg); -o-transform: rotate(-45deg); box-sizing: border-box;"> <section style="width: 0.68em; border-bottom: 1px solid rgb(106, 226, 250); margin-left: 2em; margin-top: 0.4em; box-sizing: border-box;"></section> </section> </section></section></section> </section><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0.5em 0px; position: static; box-sizing: border-box;"><section style="border-top: 1px dashed rgb(171, 171, 171); box-sizing: border-box;"></section></section></section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; position: static; box-sizing: border-box;"><section style="width: 6px; height: 6px; margin: 0.5em 0.4em 0px; border-radius: 100%; background-color: rgb(249, 110, 87); box-sizing: border-box;"> </section> <section style="height: 3em; border-left: 1px solid rgb(158, 158, 158); margin-bottom: -2.4em; margin-left: 0.6em; box-sizing: border-box;"></section> <section style="width: 5em; border-top: 1px solid rgb(158, 158, 158); box-sizing: border-box;"></section> <section style="padding: 0px 0.5em; box-sizing: border-box;"> <section style="padding: 10px; box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">2018&mdash;2019年是饮品最佳进入期</strong></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">很多人都觉得我是一个冒险主义者，因鹿角巷在进入内地市场的时候，已经不占据任何先发优势了。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">但，为什么我们最后能脱颖而出呢？我觉得和时机是有很大关系的。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">表面上看，我们进入的时期是不占任何优势的，但也因为有了喜茶、奈雪等优秀的茶饮品牌教育了市场，我们进来就不用再做任何教育市场的事情了，顾客的消费习性已被养成，所以我常说这两年是进入茶饮行业的最佳时期。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">价格战会把大批企业拖死，细分才是出路。</strong></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">尽管茶饮是一门好生意，这两年也是最佳的进入期，但这并不意味着茶饮是一门容易做的生意。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">确实某宝上花几百大洋就能买个配方开店，但越是进入没门槛的业态后期竞争就越是惨烈。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">因为没有差异化，没有特色，也没有自己的核心壁垒，最后只能在价格战中苦苦煎熬，最后你会发现大多数企业都没有经历过真正的战争，而是在价格战中熬死的。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">而你再观察喜茶，它是用一款芝士奶盖茶饮来撬开市场，在顾客喝惯了千篇一律的茶饮的时候，一个带着性感咸味的茶饮出现了，只喝一次便足以铭记；同样，鹿角巷出现之前，奶茶也是千篇一律，这个时候我们做细分，用黑糖奶茶去突围，顾客很容易被惊艳到。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">所以，茶饮细分才是未来的出路。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">茶饮+是必走模式，<span style="letter-spacing: 0px; box-sizing: border-box;">+什么取决于消费时段。</span></strong></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">很多茶饮品牌，在初入市场阶段都会选择以一个单品的形式去切入，这样做的好处就是聚焦后顾客更容易记的住。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">随着品牌运作起来开始走茶饮+模式，比如，喜茶加了冰淇淋，加了欧包；奈雪的茶也加了软欧包&hellip;&hellip;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">虽然我们鹿角巷到现在还没有加什么，但是我认为茶饮+是堂食体验店必走的模式，因为它可以：</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">1、提升客单价</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">2、增加消费时段，加深顾客记忆</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">比如拿我们和奈雪来比，同样都有饮品，顾客来我们店消费饮品可能是1天一次，可是因为奈雪有欧包，可能早上刚买了饮品，下午或晚上饿了他们又去买欧包，消费频次就变成了1天2-3次，消费时段多了，也意味着让顾客更容易记得住，在买欧包的同时也能反哺饮品的销量。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">那加什么好呢？这是很多人的疑问。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">其实在我看来，加什么取决于你的定位和消费时段。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">比如说，如果你是早上时段顾客比较多，你就应该上吐司一类适合早上食用的餐食；</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">如果你开在写字楼，中午的客流比较多，那就走轻正餐模式，沙拉、汉堡一类都是合适的；</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">如果你的店下午的客流比较多，那具有下午茶属性的欧包就比较合适。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
</section></section></section> </section> </section> <section style="width: 5em; margin-left: auto; box-sizing: border-box;"> <section style="width: 5em; border-top: 1px solid rgb(158, 158, 158); box-sizing: border-box;"></section> <section style="height: 3em; border-left: 1px solid rgb(158, 158, 158); margin-top: -2.4em; margin-left: 4.4em; box-sizing: border-box;"></section> <section style="width: 6px; height: 6px; margin-left: auto; margin-right: 0.4em; border-radius: 100%; background-color: rgb(249, 110, 87); box-sizing: border-box;"> </section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; color: rgb(62, 62, 62); line-height: 1.8; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: center; margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0.5em 0px; position: static; box-sizing: border-box;"><section style="border-top: 1px dashed rgb(171, 171, 171); box-sizing: border-box;"></section></section></section> </section><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0%; font-size: 15px; position: static; box-sizing: border-box;"><section style="display: inline-block; margin-bottom: -0.9em; overflow: hidden; box-sizing: border-box;"> <section style="width: 1.76em; height: 0.5em; margin-bottom: -0.5em; margin-left: 0.25em; border-left: 1px solid rgb(106, 226, 250); border-right: 1px solid rgb(106, 226, 250); transform: skew(-45deg); -webkit-transform: skew(-45deg); -moz-transform: skew(-45deg); -o-transform: skew(-45deg); box-sizing: border-box;"></section> <section style="width: 1.8em; height: 1.8em; margin-left: 0.5em; background-color: rgb(93, 208, 230); box-sizing: border-box;"> </section> <section style="width: 1.2em; height: 1.2em; margin-top: -0.88em; line-height: 1.2em; background-color: rgb(106, 226, 250); color: rgb(255, 255, 255); font-size: 23px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">2</p>
</section> <section style=" transform: rotate(-45deg); -webkit-transform: rotate(-45deg); -moz-transform: rotate(-45deg); -o-transform: rotate(-45deg); box-sizing: border-box;"> <section style="width: 0.68em; border-bottom: 1px solid rgb(106, 226, 250); margin-left: 2em; margin-top: 0.4em; box-sizing: border-box;"></section> </section> </section></section></section> </section><section style="display: inline-block; vertical-align: middle; width: 20%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0.5em 0px; position: static; box-sizing: border-box;"><section style="border-top: 1px dashed rgb(171, 171, 171); box-sizing: border-box;"></section></section></section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; position: static; box-sizing: border-box;"><section style="width: 6px; height: 6px; margin: 0.5em 0.4em 0px; border-radius: 100%; background-color: rgb(249, 110, 87); box-sizing: border-box;"> </section> <section style="height: 3em; border-left: 1px solid rgb(158, 158, 158); margin-bottom: -2.4em; margin-left: 0.6em; box-sizing: border-box;"></section> <section style="width: 5em; border-top: 1px solid rgb(158, 158, 158); box-sizing: border-box;"></section> <section style="padding: 0px 0.5em; box-sizing: border-box;"> <section style="padding: 10px; box-shadow: rgb(0, 0, 0) 0px 0px 0px; box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">如何靠一款黑糖奶茶，<span style="text-indent: 2em; letter-spacing: 0px; box-sizing: border-box;">5年开出200家直营店？</span></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">确切的说，我也有一个战略性的失误，其实也不算是失误了，就是我们从台北起家，后来没有选择到内地开店而是选择国外开店，致使我们来的时候茶饮品牌众多，冒牌者也无数。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">但，好在我们没有选择低价竞争，也没有选择做跟随者，而是用我们鹿角巷的方式进行突围。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">我们主要在三个方面后发制人的：</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; position: static; box-sizing: border-box;"><section style="padding: 10px; background-color: rgb(255, 202, 0); box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: center; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">空间区隔</strong></p>
</section></section></section> </section> <section style="width: 100%; text-align: right; margin-top: -4px; box-sizing: border-box;"> <section style="width: 50px; height: 4px; background-color: rgb(249, 110, 87); box-sizing: border-box;"></section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: center; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(253, 198, 32); background-color: rgb(253, 198, 32); width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">01</p>
</section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">找到符号，让顾客一眼记得住</p>
</section><section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(253, 198, 32); box-sizing: border-box;"> </section> </section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">用鹿头引发好奇，吸引女性客群进店</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&ldquo;看到红罐包装，你会很容易想到加多宝&rdquo;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&ldquo;看到M标志，你首先联想到的是麦当劳&rdquo;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&ldquo;看到红白格子，闭着眼睛都会知道我来到了西贝&rdquo;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-indent: 2em; letter-spacing: 0px; box-sizing: border-box;">所以你会发现成熟的品牌企业都有自己的符号。</span></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">我本身在开鹿角巷之前，就从事设计行业，所以太知道符号的重要性。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">所以，我们做的第一个动作就是选择用鹿头来做符号。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">为什么选择鹿头呢？第一个因为我们发现喝奶茶的多为女性，她们对小动物是拒绝不了的，鹿又在我们的文化里是有灵性的，可爱的；另外现有的茶饮品牌要不就用文字、要不就用人物头像做LOGO，很少有用动物的，这一下子会让我们的招牌醒目。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">因为成功的找到了&ldquo;鹿头&rdquo;为符号，我们才能迅速被大家记住。</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: right; margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(29, 74, 129); box-sizing: border-box;"> </section><section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">一店设三种椅子，做茶饮界的&ldquo;第三空间&rdquo;</p>
</section> </section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: left; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(29, 74, 129); background-color: rgb(29, 74, 129); text-align: center; width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; color: rgb(255, 255, 255); box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">02</p>
</section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">其实，做哪种空间还是取决于自身的定位，如果你做的是速食、外卖类型，那你门店所有动线设计都要为速度提供服务；如果你想要做成一个生活空间，让顾客在你的店里多呆一会，那则要在体验上加强。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">我们想和星巴克一样，提供一个&ldquo;第三空间&rdquo;的概念，所以你会看到当一众茶饮品牌灯光都用的特别明亮的时候，我们选择用暗一点的灯光，让它一进门就有一种想要停下来好好喝一杯咖啡的冲动。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">其次，我们的桌椅有三种，沙发、板凳和长桌椅，沙发多顾客的体验就会更好，板凳多店里的翻台速度就能提升，而长桌椅对于一些商务人群，想开个小会的人群就非常适用，具体搭配的比例我们会根据不同商圈的属性进行配比。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">​</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; position: static; box-sizing: border-box;"><section style="padding: 10px; background-color: rgb(255, 202, 0); box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: center; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">产品突围</strong></p>
</section></section></section> </section> <section style="width: 100%; text-align: right; margin-top: -4px; box-sizing: border-box;"> <section style="width: 50px; height: 4px; background-color: rgb(249, 110, 87); box-sizing: border-box;"></section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: center; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(253, 198, 32); background-color: rgb(253, 198, 32); width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">01</p>
</section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">找差异化，让顾客喝一口就记住</p>
</section><section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(253, 198, 32); box-sizing: border-box;"> </section> </section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">原创爆款黑糖奶茶，用珍珠锁客</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">很多朋友说了解鹿角巷是因为一款黑糖奶茶，的确我们能在高度竞争的市场脱颖而出主要也要归功于黑糖奶茶。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">因为我发现，顾客评价一款饮品好喝不好喝最重要的就是前3秒钟，前3秒抓住了整体感受就不会太差。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">对于一杯奶茶什么能决定前3秒感受呢？我们发现是珍珠，珍珠决定了饮品的口感层次，所以我们就在古早味奶茶的基础上，把现煮2小时的鹿丸鲜奶做成了珍珠，顾客入口就会有一种奇妙的口感，从而印象深刻。</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: right; margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(29, 74, 129); box-sizing: border-box;"> </section><section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">做彩色茶饮，让顾客自主拍照传播</p>
</section> </section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: left; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(29, 74, 129); background-color: rgb(29, 74, 129); text-align: center; width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; color: rgb(255, 255, 255); box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">02</p>
</section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">可能因为之前我是做设计相关的工作，对色彩的应用比较在行，而我又发现内地很多茶饮色调是很单一的。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">所以，为了从同质化中跳出，我们就选择从饮品色彩上去下功夫，比如过去传统奶茶就是一个颜色，那我们就用黑糖做了挂壁，让它看起来比较有纹理；比如我们会在一杯饮品里调出多种颜色，用色彩强奸顾客的眼球，这样顾客在看惯了千篇一律的饮品颜色以后，突然有一个不一样的，立马就会产生想拍照分享的冲动。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">（鹿角巷的极光特饮）</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: center; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(253, 198, 32); background-color: rgb(253, 198, 32); width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">03</p>
</section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">外包装差异化，增添趣味性。</p>
</section><section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(253, 198, 32); box-sizing: border-box;"> </section> </section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-indent: 2em; letter-spacing: 0px; box-sizing: border-box;">外包装对于一杯饮品来说也是至关重要的，我们觉得这里也是最好做差异化的地方。</span></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">当90%的门店都用细长杯装饮品的时候，我们就选择了圆滚滚的小圆杯，这样顾客很容易记得住我们。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">另外，如果是堂食店喝热饮的时候我们会有非常卡哇伊的小鹿杯套，如果是外卖带走的话会有一个小鹿的卡通包装，趣味性十足。</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: right; margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(29, 74, 129); box-sizing: border-box;"> </section><section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">一杯奶茶三种温度，给顾客极致体验</p>
</section> </section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: left; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(29, 74, 129); background-color: rgb(29, 74, 129); text-align: center; width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; color: rgb(255, 255, 255); box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">04</p>
</section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-indent: 2em; letter-spacing: 0px; box-sizing: border-box;">目前，内地市场的饮品主要是有两种温度：热的或者凉的。</span></p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">但如果去过日本的朋友可以看到，日本现在除了热的凉的还有温热这第三种温度，为的就是给顾客最极致的体验感受。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">所以，我们在国外鹿角巷的部分门店可以做到一杯奶茶有三种温度可选，但国内还没实行，还是根据顾客的需求走。</p>
</section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 10px 0%; position: static; box-sizing: border-box;"><section style="display: inline-block; vertical-align: bottom; width: 12%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 3px 0px; text-align: center; position: static; box-sizing: border-box;"><section style="display: inline-block; border: 1px solid rgb(253, 198, 32); background-color: rgb(253, 198, 32); width: 1.8em; height: 1.8em; line-height: 1.8em; border-radius: 100%; margin-left: auto; margin-right: auto; font-size: 18px; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">05</p>
</section></section></section> </section><section style="display: inline-block; vertical-align: bottom; width: 88%; box-sizing: border-box;"> <section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 0px 0% 5px; position: static; box-sizing: border-box;"><section style="display: inline-block; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: bottom; border-bottom: 1px dashed rgb(175, 175, 175); margin-bottom: 0.25em; padding-left: 5px; padding-right: 5px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">逢节日必做爆品，让年轻客群喜爱</p>
</section><section style="display: inline-block; vertical-align: bottom; width: 0.5em; height: 0.5em; border-radius: 50%; background-color: rgb(253, 198, 32); box-sizing: border-box;"> </section> </section></section></section> </section></section></section><section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">因为喝奶茶的客群，大多数都是年轻人，而且以女性居多，她们是喜欢仪式感的一代。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">所以针对客群的这一特点，我们选择在情人节、圣诞节、万圣节这样的节日上一些爆品。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">比如，去年圣诞节我们就用翻糖蛋糕、爆米花等产品做了一款十分有圣诞气息的产品，一经推出就迅速被抢光，花几十元钱却能买到一天的节日好心情，实际上顾客对这块的需求很大，有待我们去开发。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">营销突围：</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">请明星做一日店长，做品牌防火墙</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&ldquo;这家鹿角巷是你们的吗？&rdquo;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&ldquo;你是鹿角巷的创始人吗？&rdquo;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">&hellip;&hellip;</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">创业5年，这些问题始终伴随着我，要问我这几年最痛苦的事情大概就是被冒牌店模仿，所以在这里也提醒大家，要从一开始就树立品牌意识，建立防火墙。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">为了区别于冒牌店，我们这两年一直在做一个活动，那就是请明星来店里做一日店长，这样做的好处有两个：</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">一个就是能够区别于假店，毕竟这么做成本不低；</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">第二在中国最具有流量的还是明星，而追星的这部分人又刚好和我们的客群吻合，所以从另外一个角度来说也能为我们制造话题引起关注。</p>
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">比如说最近，《延禧攻略》大热，我们就请到了扮演海兰察的演员来店里，通过活动建立起自己的品牌防火墙。</p>
</section></section></section> </section> </section> <section style="width: 5em; margin-left: auto; box-sizing: border-box;"> <section style="width: 5em; border-top: 1px solid rgb(158, 158, 158); box-sizing: border-box;"></section> <section style="height: 3em; border-left: 1px solid rgb(158, 158, 158); margin-top: -2.4em; margin-left: 4.4em; box-sizing: border-box;"></section> <section style="width: 6px; height: 6px; margin-left: auto; margin-right: 0.4em; border-radius: 100%; background-color: rgb(249, 110, 87); box-sizing: border-box;"> </section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin-top: 10px; margin-bottom: 10px; text-align: center; position: static; box-sizing: border-box;"><section style="max-width: 100%; font-size: 0px; padding-bottom: 3px; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: middle; box-sizing: border-box;"> <section style="width: 5px; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> <section style="width: 1px; height: 5px; margin: -3px auto 0px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> <section style="margin: -1px -5px 0px; width: 100%; display: inline-block; vertical-align: middle; padding: 0px 8px; box-sizing: border-box;"> <section style="width: 100%; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> <section style="display: inline-block; vertical-align: middle; box-sizing: border-box;"> <section style="width: 5px; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> <section style="width: 1px; height: 5px; margin: -3px auto 0px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> </section> <section style="border-left: 1px solid rgb(95, 156, 239); border-right: 1px solid rgb(95, 156, 239); margin: 0px 2px 5px; border-top-color: rgb(95, 156, 239); border-bottom-color: rgb(95, 156, 239); box-sizing: border-box;"> <section class="V5" style="box-sizing: border-box;" powered-by="xiumi.us"><section style="padding: 10px; position: static; box-sizing: border-box;"><section style="text-align: justify; font-size: 15px; line-height: 2; color: rgb(255, 129, 36); box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">尽管和邱茂庭的对话只有短短的两个小时，但却给我带来了很深的触动，我们老说市场竞争激烈，老是抱怨客流少，其实品牌存在的意义就是不断创造需求开发用户，就看我们能不能心领神会用户在当下真正的需求是什么，从而成为某一业态中的超级品牌。</p>
</section></section></section> </section> <section style="max-width: 100%; font-size: 0px; box-sizing: border-box;"> <section style="display: inline-block; vertical-align: middle; box-sizing: border-box;"> <section style="width: 5px; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> <section style="width: 1px; height: 5px; margin: -3px auto 0px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> <section style="margin: -1px -5px 0px; width: 100%; display: inline-block; vertical-align: middle; padding: 0px 8px; box-sizing: border-box;"> <section style="width: 100%; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> <section style="display: inline-block; vertical-align: middle; box-sizing: border-box;"> <section style="width: 5px; height: 1px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> <section style="width: 1px; height: 5px; margin: -3px auto 0px; background-color: rgb(95, 156, 239); box-sizing: border-box;"></section> </section> </section></section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="margin: 8px 0% 10px; position: static; box-sizing: border-box;"><section style="background-color: rgb(105, 143, 187); height: 1px; box-sizing: border-box;"></section> </section></section><section class="V5" style="position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="position: static; box-sizing: border-box;"><section style="text-align: right; font-size: 12px; color: rgb(160, 160, 160); box-sizing: border-box;">
<p style="margin: 0px; padding: 0px; box-sizing: border-box;">（本文汇编于网上，如有侵权，请联系删除。）</p>
</section></section></section></section>